name: docker_build_qa

on:
  push:
    branches:
      - qa

jobs:
  docker_build:
    uses: ./.github/workflows/docker_build.yml
    with:
      env: "qa"
    secrets: inherit
    name: QA Docker Build
