name: docker_build_prod

on:
  push:
    branches:
      - main
      - master

jobs:
  docker_build:
    uses: ./.github/workflows/docker_build.yml
    with:
      env: "prod"
    secrets: inherit
    name: Prod Docker Build
